# Generated by Django 5.1.2 on 2024-11-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_custom_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom_User',
        ),
    ]
